# This is a basic workflow to help you get started with Actions

name: Deploy from Nuxt to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0

      # Build static site
      - name: Run a multi-line script
        run: |
             cd $GITHUB_WORKSPACE/src
             npm ci
             npx nuxi generate
             
      # Upload artifact
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@main
        with:
          path: $GITHUB_WORKSPACE/src/dist

  deploy:
    runs-on: ubuntu-latest
    environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1-beta
        id: deployment
